# Generated by Django 5.0.3 on 2024-05-05 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_mbit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='mbit',
        ),
        migrations.AddField(
            model_name='profile',
            name='mbti',
            field=models.TextField(max_length=10, null=True),
        ),
    ]
