# Generated by Django 5.0.3 on 2024-04-29 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='feel',
            field=models.CharField(default='좋아용', max_length=50),
            preserve_default=False,
        ),
    ]
