# Generated by Django 5.0.3 on 2024-05-05 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_post_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
    ]
